import { rootNode, childOfType, walk, stringLiteralValue } from './tree.js';
import data from './jsondata/jsgen.data.json' with { type: 'json' };

const JS_STRING_BUILTINS = data.jsStringBuiltins;
const SUPPORTED_WASM_LOCATIONS = data.supportedWasmLocations;
const SUPPORTED_MODULE_FORMATS = data.supportedModuleFormats;

export function jsgen(treeOrNode, binary, { mode = 'program', profile = null, where = 'base64', moduleFormat = 'esm', metadata = {} } = {}) {
    if (!SUPPORTED_WASM_LOCATIONS.includes(where))
        throw new Error(`Unsupported wasm location "${where}". Expected base64, relative_url, or local_file_node.`);
    if (!SUPPORTED_MODULE_FORMATS.includes(moduleFormat))
        throw new Error(`Unsupported module format "${moduleFormat}". Expected esm.`);

    const root = rootNode(treeOrNode);
    const { strings, exportNames } = analyze(root, mode);
    const moduleImports = groupImportsByModule(root, profile);
    const needsImports = moduleImports.length > 0;
    const needsNodeImports = moduleImports.some(({ autoResolve }) => autoResolve);
    const lines = ['// Generated by utu compiler — do not edit'];

    if (where === 'base64') lines.push(
        '',
        `const __b64 = "${toBase64(binary)}";`,
        'const __decodeBase64 = s => { const bin = atob(s), out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i); return out; };',
        'const __wasmBytes = __decodeBase64(__b64);',
    );

    if (where === 'relative_url') lines.push('', 'const __wasmUrl = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');
    if (where === 'local_file_node') lines.push('', 'const __wasmPath = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');

    if (strings.length) lines.push('', `const __strings = [${strings.map(value => JSON.stringify(value)).join(', ')}];`);
    lines.push('', `const __jsStringBuiltins = {\n${JS_STRING_BUILTINS.map(({ name, expression }) => `  ${name}: ${expression},`).join('\n')}\n};`);
    lines.push('', `export const metadata = ${JSON.stringify({
        tests: metadata.tests ?? [],
        benches: metadata.benches ?? [],
    })};`);
    lines.push('', [
        `export const DEFAULT_BENCHMARK_OPTIONS = Object.freeze(${JSON.stringify(data.defaultBenchmarkOptions)});`,
        'const __defaultFormatError = error => error instanceof Error ? error.message : String(error);',
        'const __defaultNow = () => performance.now();',
        'const __defaultClock = () => typeof process !== "undefined" && process?.hrtime?.bigint',
        '  ? { nowNs: () => Number(process.hrtime.bigint()) }',
        '  : { nowNs: () => Math.round(performance.now() * 1e6) };',
        'const __benchmarkRate = (iterations, elapsedNs) => elapsedNs <= 0 ? 0 : iterations / (elapsedNs / 1e9);',
        `const __iterationsPerSecondFormatThresholds = ${JSON.stringify(data.iterationsPerSecondFormatThresholds)};`,
        'const __formatIterationsPerSecond = value => {',
        '  for (const entry of __iterationsPerSecondFormatThresholds) {',
        '    if (value >= entry.min) return `${(value / entry.divisor).toFixed(entry.digits)}${entry.suffix}`;',
        '  }',
        '  return `${value.toFixed(2)} iter/s`;',
        '};',
        `const __durationNsFormatThresholds = ${JSON.stringify(data.durationNsFormatThresholds)};`,
        'const __formatDurationNs = value => {',
        '  for (const entry of __durationNsFormatThresholds) {',
        '    if (value >= entry.min) return `${(value / entry.divisor).toFixed(entry.digits)}${entry.suffix}`;',
        '  }',
        '  return `${value.toFixed(0)}ns`;',
        '};',
        'const __normalizeBenchmarkOptions = options => ({',
        '  seconds: Number.isFinite(options?.seconds) && options.seconds > 0 ? options.seconds : DEFAULT_BENCHMARK_OPTIONS.seconds,',
        '  samples: Number.isFinite(options?.samples) ? Math.max(1, Math.floor(options.samples)) : DEFAULT_BENCHMARK_OPTIONS.samples,',
        '  warmup: Number.isFinite(options?.warmup) ? Math.max(0, Math.floor(options.warmup)) : DEFAULT_BENCHMARK_OPTIONS.warmup,',
        '});',
        'const __selectEntry = (entries, ordinal) => entries[ordinal];',
        'const __invokeExport = async (exports, exportName, args = []) => ({ logs: [], result: await exports[exportName](...args) });',
        'const __timeInvocation = async (run, clock) => {',
        '  const startNs = clock.nowNs();',
        '  await run();',
        '  return Math.max(0, clock.nowNs() - startNs);',
        '};',
        'const __clampIterations = value => !Number.isFinite(value) || value < 1 ? 1 : Math.max(1, Math.min(0x7fffffff, Math.round(value)));',
        'const __projectIterations = (iterations, elapsedNs, targetNs) => elapsedNs <= 0',
        '  ? __clampIterations(iterations * 10)',
        '  : __clampIterations(Math.round(iterations * (targetNs / elapsedNs)));',
        'const __calibrateIterations = async (bench, targetNs, initialIterations, clock) => {',
        '  let iterations = __clampIterations(initialIterations);',
        '  let elapsedNs = await __timeInvocation(() => bench(iterations), clock);',
        '  while (elapsedNs < targetNs / 10 && iterations < 0x7fffffff) {',
        '    const scale = elapsedNs <= 0 ? 10 : Math.max(2, Math.ceil((targetNs / 10) / elapsedNs));',
        '    const next = __clampIterations(iterations * scale);',
        '    if (next === iterations) break;',
        '    iterations = next;',
        '    elapsedNs = await __timeInvocation(() => bench(iterations), clock);',
        '  }',
        '  return __projectIterations(iterations, elapsedNs, targetNs);',
        '};',
        'const __mergeCounts = (target, values) => {',
        '  for (let i = 0; i < values.length; i += 1) target[i] = (target[i] ?? 0) + (values[i] ?? 0);',
        '};',
        'export async function runTest(exports, ordinal, { formatError = __defaultFormatError, now = __defaultNow } = {}) {',
        '  const test = __selectEntry(metadata.tests, ordinal);',
        '  const start = now();',
        '  try {',
        '    const execution = await __invokeExport(exports, test.exportName, []);',
        '    return { name: test.name, exportName: test.exportName, durationMs: now() - start, error: undefined, logs: execution.logs, passed: true };',
        '  } catch (error) {',
        '    return { name: test.name, exportName: test.exportName, durationMs: now() - start, error: formatError(error), logs: [], passed: false };',
        '  }',
        '}',
        'export async function runBenchmark(exports, ordinal, options = {}, measureOptions = {}) {',
        '  const bench = __selectEntry(metadata.benches, ordinal);',
        '  const settings = __normalizeBenchmarkOptions(options);',
        '  const targetNs = Math.floor(settings.seconds * 1e9);',
        '  const profile = measureOptions.profile ?? null;',
        '  const clock = measureOptions.clock ?? __defaultClock();',
        '  const benchFn = exports[bench.exportName];',
        '  let estimate = 1;',
        '  for (let warmupIndex = 0; warmupIndex < settings.warmup; warmupIndex += 1) estimate = await __calibrateIterations(benchFn, targetNs, estimate, clock);',
        '  const runs = [];',
        '  const profileCounts = [];',
        '  let logs = [];',
        '  for (let sampleIndex = 0; sampleIndex < settings.samples; sampleIndex += 1) {',
        '    const iterations = __clampIterations(estimate);',
        '    profile?.reset?.();',
        '    const startNs = clock.nowNs();',
        '    const execution = await __invokeExport(exports, bench.exportName, [iterations]);',
        '    const elapsedNs = Math.max(0, clock.nowNs() - startNs);',
        '    estimate = __projectIterations(iterations, elapsedNs, targetNs);',
        '    logs = execution.logs;',
        '    runs.push({ durationMs: elapsedNs / 1e6, elapsedNs, iterations });',
        '    if (profile?.snapshot) __mergeCounts(profileCounts, profile.snapshot());',
        '  }',
        '  const durations = runs.map(run => run.durationMs);',
        '  const elapsedNs = runs.map(run => run.elapsedNs);',
        '  const durationMs = durations.reduce((sum, value) => sum + value, 0);',
        '  const meanMs = durationMs / durations.length;',
        '  const iterationTotal = runs.reduce((sum, run) => sum + run.iterations, 0);',
        '  const rates = runs.map(run => __benchmarkRate(run.iterations, run.elapsedNs));',
        '  const meanRate = durationMs <= 0 ? 0 : iterationTotal / (durationMs / 1000);',
        '  const summary = `${bench.name}: mean ${__formatIterationsPerSecond(meanRate)}, min ${__formatIterationsPerSecond(Math.min(...rates))}, max ${__formatIterationsPerSecond(Math.max(...rates))}, ${__formatDurationNs(iterationTotal > 0 ? (durationMs / iterationTotal) * 1e6 : 0)}/iter, ${settings.seconds.toFixed(3)}s target, ${runs.map(run => run.iterations).join(", ")} iterations`;',
        '  return {',
        '    name: bench.name,',
        '    exportName: bench.exportName,',
        '    durationMs,',
        '    logs,',
        '    maxMs: Math.max(...durations),',
        '    meanMs,',
        '    minMs: Math.min(...durations),',
        '    perIterationMs: iterationTotal > 0 ? durationMs / iterationTotal : 0,',
        '    sampleDurationsMs: durations,',
        '    sampleElapsedNs: elapsedNs,',
        '    iterations: runs.map(run => run.iterations),',
        '    iterationTotal,',
        '    profileCounts,',
        '    summary,',
        '  };',
        '}',
    ].join('\n'));

    if (needsImports) lines.push('', [
        'const __globalObject = typeof globalThis !== "undefined" ? globalThis : undefined;',
        'const __importPaths = (moduleName, importName) => {',
        '  const paths = [[importName]];',
        '  const parts = importName.split("_").filter(Boolean);',
        '  if (parts.length > 1) paths.push(parts);',
        '  if (moduleName === "es" && parts.length > 1) {',
        '    const [head, ...tail] = parts;',
        '    const headVariants = [head];',
        '    const capitalized = head ? head[0].toUpperCase() + head.slice(1) : head;',
        '    if (capitalized && !headVariants.includes(capitalized)) headVariants.push(capitalized);',
        '    const upper = head.toUpperCase();',
        '    if (upper && !headVariants.includes(upper)) headVariants.push(upper);',
        '    for (const variant of headVariants.slice(1)) paths.push([variant, ...tail]);',
        '  }',
        '  return paths;',
        '};',
        'const __resolveBindingPath = (root, path) => {',
        '  if (!root || (typeof root !== "object" && typeof root !== "function")) return null;',
        '  let value = root;',
        '  for (const segment of path) {',
        '    if (!value || (typeof value !== "object" && typeof value !== "function") || !(segment in value)) return null;',
        '    value = value[segment];',
        '  }',
        '  return value;',
        '};',
        'const __resolveHostImport = (moduleObject, moduleName, importName) => {',
        '  for (const source of [moduleObject, moduleName === "es" ? __globalObject : undefined]) {',
        '    if (source === undefined) continue;',
        '    for (const path of __importPaths(moduleName, importName)) {',
        '      const resolved = __resolveBindingPath(source, path);',
        '      if (resolved) return resolved;',
        '    }',
        '  }',
        '  throw new Error(`Missing host import "${importName}" from "${moduleName}"`);',
        '};',
    ].join('\n'));

    if (needsNodeImports) lines.push('', [
        'const __importHostModule = async specifier => {',
        '  try { return await import(specifier); }',
        '  catch (error) { throw new Error(`Failed to auto-resolve host module "${specifier}": ${error instanceof Error ? error.message : String(error)}`); }',
        '};',
    ].join('\n'));

    lines.push('', 'export async function instantiate() {');
    for (const group of moduleImports)
        if (group.autoResolve)
            lines.push(`  const ${group.ref} = await __importHostModule(${JSON.stringify(group.module)});`);
    if (where === 'base64') lines.push('  const __wasm = __wasmBytes;');
    if (where === 'relative_url') lines.push('  const __wasm = await (await fetch(__wasmUrl)).arrayBuffer();');
    if (where === 'local_file_node') lines.push('  const __wasm = await (await import("node:fs/promises")).readFile(__wasmPath);');
    lines.push('  const __result = await WebAssembly.instantiate(__wasm, {');
    if (strings.length) lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [i, s])),');
    lines.push('    "wasm:js-string": __jsStringBuiltins,');
    for (const group of moduleImports) {
            const moduleRef = group.autoResolve
                ? group.ref
                : group.module === 'es'
                    ? '__globalObject'
                    : group.module === '__utu_profile'
                        ? '__globalObject?.__utu_profile'
                        : 'undefined';
        lines.push(`    ${JSON.stringify(group.module)}: {`);
        for (const entry of group.entries) {
            const binding = `__resolveHostImport(${moduleRef}, ${JSON.stringify(group.module)}, ${JSON.stringify(entry.name)})`;
            lines.push(`      ${JSON.stringify(entry.name)}: ${binding},`);
        }
        lines.push('    },');
    }
    lines.push('  });', '  return (__result.instance ?? __result).exports;', '}');
    if (exportNames.length) lines.push('', `// Exported functions: ${exportNames.join(', ')}`);
    return lines.join('\n');
}

function analyze(root, mode) {
    const strings = new Map(), exportNames = [];
    const fnBodies = [], globalBodies = [], testBodies = [], benchBodies = [];
    const addBody = (bucket, node) => node && bucket.push(node);

    for (const item of root.namedChildren) {
        switch (item.type) {
            case 'fn_decl':
                addBody(fnBodies, childOfType(item, 'block'));
                break;
            case 'export_decl': {
                const fn = childOfType(item, 'fn_decl');
                exportNames.push(childOfType(fn, 'identifier').text);
                addBody(fnBodies, childOfType(fn, 'block'));
                break;
            }
            case 'global_decl':
                addBody(globalBodies, item.namedChildren.at(-1));
                break;
            case 'test_decl':
                if (mode === 'test') addBody(testBodies, childOfType(item, 'block'));
                break;
            case 'bench_decl':
                if (mode !== 'bench') break;
                const named = childOfType(item, 'setup_decl')?.namedChildren ?? [];
                benchBodies.push(...named.slice(0, -1));
                addBody(benchBodies, childOfType(named.at(-1), 'block'));
                break;
        }
    }

    for (const node of [...fnBodies, ...globalBodies, ...testBodies, ...benchBodies]) walk(node, child => {
        const value = stringLiteralValue(child);
        if (value !== null && !strings.has(value)) strings.set(value, strings.size);
    });
    return { strings: [...strings.keys()], exportNames };
}

function groupImportsByModule(root, profile = null) {
    const groups = new Map();
    const groupFor = (module) => {
        if (!groups.has(module)) groups.set(module, {
            module,
            entries: [],
            autoResolve: module.startsWith('node:'),
            ref: `__host_module_${groups.size}`,
        });
        return groups.get(module);
    };

    for (const item of root.namedChildren) {
        if (item.type !== 'import_decl') continue;
        const entry = parseImportDecl(item);
        groupFor(entry.module).entries.push(entry);
    }
    if (profile === 'ticks') groupFor('__utu_profile').entries.push({ name: 'tick', kind: 'function' });
    return [...groups.values()];
}

function parseImportDecl(node) {
    const [moduleNode, nameNode] = node.namedChildren;
    const module = moduleNode.text.slice(1, -1);
    const name = nameNode.text;
    if (node.text.includes('(')) {
        return {
            kind: 'function',
            module,
            name,
            paramCount: childOfType(node, 'import_param_list')?.namedChildren.length ?? 0,
        };
    }
    return { kind: 'value', module, name };
}

function toBase64(bytes) {
    let bin = '';
    for (const byte of bytes) bin += String.fromCharCode(byte);
    return btoa(bin);
}
