import { rootNode, namedChildren, childOfType, walk, stringLiteralValue } from './tree.js';
import data from './jsondata/jsgen.data.json' with { type: 'json' };

const JS_STRING_BUILTINS = data.jsStringBuiltins;
const SUPPORTED_WASM_LOCATIONS = data.supportedWasmLocations;
const SUPPORTED_MODULE_FORMATS = data.supportedModuleFormats;

export function jsgen(treeOrNode, binary, { mode = 'program', profile = null, where = 'base64', moduleFormat = 'esm', metadata = {} } = {}) {
    if (!SUPPORTED_WASM_LOCATIONS.includes(where))
        throw new Error(`Unsupported wasm location "${where}". Expected base64, relative_url, or local_file_node.`);
    if (!SUPPORTED_MODULE_FORMATS.includes(moduleFormat))
        throw new Error(`Unsupported module format "${moduleFormat}". Expected esm.`);

    const root = rootNode(treeOrNode);
    const { strings, exportNames } = analyze(root, mode);
    const moduleImports = groupImportsByModule(root, profile);
    const needsImports = moduleImports.length > 0;
    const needsNodeImports = moduleImports.some(({ autoResolve }) => autoResolve);
    const lines = ['// Generated by utu compiler — do not edit'];

    if (where === 'base64') lines.push(
        '',
        `const __b64 = "${toBase64(binary)}";`,
        'const __decodeBase64 = s => { const bin = atob(s), out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i); return out; };',
        'const __wasmBytes = __decodeBase64(__b64);',
    );

    if (where === 'relative_url') lines.push('', 'const __wasmUrl = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');
    if (where === 'local_file_node') lines.push('', 'const __wasmPath = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');

    if (strings.length) lines.push('', `const __strings = [${strings.map(value => JSON.stringify(value)).join(', ')}];`);
    lines.push('', `const __jsStringBuiltins = {\n${JS_STRING_BUILTINS.map(({ name, expression }) => `  ${name}: ${expression},`).join('\n')}\n};`);
    lines.push('', `export const metadata = ${JSON.stringify({
        tests: metadata.tests ?? [],
        benches: metadata.benches ?? [],
    })};`);
    lines.push('', renderSnippetLines(data.runtimePreludeLines, {
        __DEFAULT_BENCHMARK_OPTIONS__: JSON.stringify(data.defaultBenchmarkOptions),
        __ITERATIONS_PER_SECOND_FORMAT_THRESHOLDS__: JSON.stringify(data.iterationsPerSecondFormatThresholds),
        __DURATION_NS_FORMAT_THRESHOLDS__: JSON.stringify(data.durationNsFormatThresholds),
    }));

    if (needsImports) lines.push('', renderSnippetLines(data.resolveHostImportLines));

    if (needsNodeImports) lines.push('', renderSnippetLines(data.importHostModuleLines));

    lines.push('', 'export async function instantiate() {');
    for (const group of moduleImports)
        if (group.autoResolve)
            lines.push(`  const ${group.ref} = await __importHostModule(${JSON.stringify(group.module)});`);
    if (where === 'base64') lines.push('  const __wasm = __wasmBytes;');
    if (where === 'relative_url') lines.push('  const __wasm = await (await fetch(__wasmUrl)).arrayBuffer();');
    if (where === 'local_file_node') lines.push('  const __wasm = await (await import("node:fs/promises")).readFile(__wasmPath);');
    lines.push('  const __result = await WebAssembly.instantiate(__wasm, {');
    if (strings.length) lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [i, s])),');
    lines.push('    "wasm:js-string": __jsStringBuiltins,');
    for (const group of moduleImports) {
            const moduleRef = group.autoResolve
                ? group.ref
                : group.module === 'es'
                    ? 'globalThis'
                    : group.module === '__utu_profile'
                        ? 'globalThis.__utu_profile'
                        : 'undefined';
        lines.push(`    ${JSON.stringify(group.module)}: {`);
        for (const entry of group.entries) {
            const binding = `__resolveHostImport(${moduleRef}, ${JSON.stringify(group.module)}, ${JSON.stringify(entry.name)})`;
            lines.push(`      ${JSON.stringify(entry.name)}: ${binding},`);
        }
        lines.push('    },');
    }
    lines.push('  });', '  return (__result.instance ?? __result).exports;', '}');
    if (exportNames.length) lines.push('', `// Exported functions: ${exportNames.join(', ')}`);
    return lines.join('\n');
}

function analyze(root, mode) {
    const strings = new Map(), exportNames = [];
    const fnBodies = [], globalBodies = [], testBodies = [], benchBodies = [];
    const addBody = (bucket, node) => node && bucket.push(node);

    for (const item of namedChildren(root)) {
        switch (item.type) {
            case 'fn_decl':
                addBody(fnBodies, childOfType(item, 'block'));
                break;
            case 'export_decl': {
                const fn = childOfType(item, 'fn_decl');
                exportNames.push(childOfType(fn, 'identifier').text);
                addBody(fnBodies, childOfType(fn, 'block'));
                break;
            }
            case 'global_decl':
                addBody(globalBodies, namedChildren(item).at(-1));
                break;
            case 'test_decl':
                if (mode === 'test') addBody(testBodies, childOfType(item, 'block'));
                break;
            case 'bench_decl':
                if (mode !== 'bench') break;
                const named = namedChildren(childOfType(item, 'setup_decl'));
                benchBodies.push(...named.slice(0, -1));
                addBody(benchBodies, childOfType(named.at(-1), 'block'));
                break;
        }
    }

    for (const node of [...fnBodies, ...globalBodies, ...testBodies, ...benchBodies]) walk(node, child => {
        const value = stringLiteralValue(child);
        if (value !== null && !strings.has(value)) strings.set(value, strings.size);
    });
    return { strings: [...strings.keys()], exportNames };
}

function groupImportsByModule(root, profile = null) {
    const groups = new Map();
    const groupFor = (module) => {
        if (!groups.has(module)) groups.set(module, {
            module,
            entries: [],
            autoResolve: module.startsWith('node:'),
            ref: `__host_module_${groups.size}`,
        });
        return groups.get(module);
    };

    for (const item of namedChildren(root)) {
        if (item.type !== 'import_decl') continue;
        const entry = parseImportDecl(item);
        groupFor(entry.module).entries.push(entry);
    }
    if (profile === 'ticks') groupFor('__utu_profile').entries.push({ name: 'tick', kind: 'function' });
    return [...groups.values()];
}

function parseImportDecl(node) {
    const [moduleNode, nameNode] = namedChildren(node);
    const module = moduleNode.text.slice(1, -1);
    const name = nameNode.text;
    if (node.text.includes('(')) {
        return {
            kind: 'function',
            module,
            name,
            paramCount: namedChildren(childOfType(node, 'import_param_list')).length,
        };
    }
    return { kind: 'value', module, name };
}

function toBase64(bytes) {
    let bin = '';
    for (const byte of bytes) bin += String.fromCharCode(byte);
    return btoa(bin);
}

function renderSnippetLines(lines, replacements = {}) {
    return lines.map(line => Object.entries(replacements).reduce(
        (rendered, [key, value]) => rendered.replaceAll(key, value),
        line,
    )).join('\n');
}
