import { parseHostImportName } from './parser.js';
import { rootNode, namedChildren, childOfType, walk, stringLiteralValue } from './tree.js';
import data from './jsondata/jsgen.data.json' with { type: 'json' };

const SUPPORTED_WASM_LOCATIONS = data.supportedWasmLocations;
const SUPPORTED_MODULE_FORMATS = data.supportedModuleFormats;

export function jsgen(treeOrNode, binary, { mode = 'program', profile = null, where = 'base64', moduleFormat = 'esm', metadata = {} } = {}) {
    if (!SUPPORTED_WASM_LOCATIONS.includes(where))
        throw new Error(`Unsupported wasm location "${where}". Expected base64, relative_url, or local_file_node.`);
    if (!SUPPORTED_MODULE_FORMATS.includes(moduleFormat))
        throw new Error(`Unsupported module format "${moduleFormat}". Expected esm.`);

    const root = rootNode(treeOrNode);
    const { strings, exportNames } = analyze(root, mode);
    const moduleImports = groupImportsByModule(root, profile);
    const inlineJsImports = collectInlineJsImports(root);
    const needsNodeImports = moduleImports.some(({ autoResolve }) => autoResolve);
    const lines = ['// Generated by utu compiler — do not edit'];

    if (where === 'base64') lines.push(
        '',
        `const __b64 = "${toBase64(binary)}";`,
        'const __decodeBase64 = s => { const bin = atob(s), out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i); return out; };',
        'const __wasmBytes = __decodeBase64(__b64);',
    );

    if (where === 'relative_url') lines.push('', 'const __wasmUrl = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');
    if (where === 'local_file_node') lines.push('', 'const __wasmPath = new URL(import.meta.url.replace(/\\.(?:[cm]?js|mjs)$/u, ".wasm"));');

    if (strings.length) lines.push('', `const __strings = [${strings.map(value => JSON.stringify(value)).join(', ')}];`);
    for (const entry of inlineJsImports)
        lines.push('', `const ${entry.ref} = (${entry.jsSource});`);
    lines.push('', `export const metadata = ${JSON.stringify({
        tests: metadata.tests ?? [],
        benches: metadata.benches ?? [],
    })};`);
    lines.push('', renderSnippetLines(data.runtimePreludeLines, {
        __DEFAULT_BENCHMARK_OPTIONS__: JSON.stringify(data.defaultBenchmarkOptions),
        __ITERATIONS_PER_SECOND_FORMAT_THRESHOLDS__: JSON.stringify(data.iterationsPerSecondFormatThresholds),
        __DURATION_NS_FORMAT_THRESHOLDS__: JSON.stringify(data.durationNsFormatThresholds),
    }));

    if (needsNodeImports) lines.push('', renderSnippetLines(data.importHostModuleLines));

    lines.push('', 'export async function instantiate(__wasmOverride, __hostImports = {}) {');
    for (const group of moduleImports)
        if (group.autoResolve)
            lines.push(`  const ${group.ref} = await __importHostModule(${JSON.stringify(group.module)});`);
    if (where === 'base64') lines.push('  const __wasm = __wasmOverride ?? __wasmBytes;');
    if (where === 'relative_url') lines.push('  const __wasm = __wasmOverride ?? await (await fetch(__wasmUrl)).arrayBuffer();');
    if (where === 'local_file_node') lines.push('  const __wasm = __wasmOverride ?? await (await import("node:fs/promises")).readFile(__wasmPath);');
    lines.push('  const __imports = {');
    if (strings.length) lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [i, s])),');
    for (const group of moduleImports) {
        const moduleRef = group.autoResolve
            ? group.ref
            : null;
        lines.push(`    ${JSON.stringify(group.module)}: {`);
        for (const entry of group.entries) {
            const binding = renderImportBinding(group, entry, moduleRef);
            lines.push(`      ${JSON.stringify(entry.hostName)}: ${binding},`);
        }
        lines.push('    },');
    }
    lines.push('  };', '  const __result = await WebAssembly.instantiate(__wasm, __imports);', '  return (__result.instance ?? __result).exports;', '}');
    if (exportNames.length) lines.push('', `// Exported functions: ${exportNames.join(', ')}`);
    return lines.join('\n');
}

function analyze(root, mode) {
    const strings = new Map(), exportNames = [];
    const fnBodies = [], globalBodies = [], testBodies = [], benchBodies = [];
    const addBody = (bucket, node) => node && bucket.push(node);

    for (const item of namedChildren(root)) {
        switch (item.type) {
            case 'fn_decl':
                addBody(fnBodies, childOfType(item, 'block'));
                break;
            case 'export_decl': {
                const fn = childOfType(item, 'fn_decl');
                exportNames.push(childOfType(fn, 'identifier').text);
                addBody(fnBodies, childOfType(fn, 'block'));
                break;
            }
            case 'global_decl':
                addBody(globalBodies, namedChildren(item).at(-1));
                break;
            case 'test_decl':
                if (mode === 'test') addBody(testBodies, childOfType(item, 'block'));
                break;
            case 'bench_decl':
                if (mode !== 'bench') break;
                const named = namedChildren(childOfType(item, 'setup_decl'));
                benchBodies.push(...named.slice(0, -1));
                addBody(benchBodies, childOfType(named.at(-1), 'block'));
                break;
        }
    }

    for (const node of [...fnBodies, ...globalBodies, ...testBodies, ...benchBodies]) walk(node, child => {
        const value = stringLiteralValue(child);
        if (value !== null && !strings.has(value)) strings.set(value, strings.size);
    });
    return { strings: [...strings.keys()], exportNames };
}

function groupImportsByModule(root, profile = null) {
    const groups = new Map();
    const groupFor = (module) => {
        if (!groups.has(module)) groups.set(module, {
            module,
            entries: [],
            autoResolve: module.startsWith('node:'),
            ref: `__host_module_${groups.size}`,
        });
        return groups.get(module);
    };

    for (const item of namedChildren(root)) {
        if (item.type !== 'import_decl' && item.type !== 'jsgen_decl') continue;
        const entry = item.type === 'import_decl'
            ? parseImportDecl(item)
            : parseJsgenDecl(item);
        groupFor(entry.module).entries.push(entry);
    }
    if (profile === 'ticks') groupFor('__utu_profile').entries.push({ name: 'tick', hostName: 'tick', hostPath: ['tick'], kind: 'function' });
    return [...groups.values()];
}

function parseImportDecl(node) {
    const [moduleNode, nameNode] = namedChildren(node);
    const module = moduleNode.text.slice(1, -1);
    const name = nameNode.text;
    const { hostName, hostPath } = parseHostImportName(name);
    if (node.text.includes('(')) {
        return {
            kind: 'function',
            module,
            name,
            hostName,
            hostPath,
            paramCount: namedChildren(childOfType(node, 'import_param_list')).length,
            returnType: parseReturnTypeNode(childOfType(node, 'return_type')),
        };
    }
    return { kind: 'value', module, name, hostName, hostPath };
}

function parseJsgenDecl(node) {
    const [sourceNode, nameNode] = namedChildren(node);
    return {
        kind: 'inline_js',
        module: '__utu_jsgen',
        name: nameNode.text,
        hostName: nameNode.text,
        ref: `__inline_js_${nameNode.text}`,
        jsSource: sourceNode.text.slice(1, -1),
    };
}

function collectInlineJsImports(root) {
    const seen = new Set();
    const entries = [];
    for (const item of namedChildren(root)) {
        if (item.type !== 'jsgen_decl') continue;
        const entry = parseJsgenDecl(item);
        if (seen.has(entry.ref)) continue;
        seen.add(entry.ref);
        entries.push(entry);
    }
    return entries;
}

function toBase64(bytes) {
    let bin = '';
    for (const byte of bytes) bin += String.fromCharCode(byte);
    return btoa(bin);
}

function renderSnippetLines(lines, replacements = {}) {
    return lines.map(line => Object.entries(replacements).reduce(
        (rendered, [key, value]) => rendered.replaceAll(key, value),
        line,
    )).join('\n');
}

function renderHostImportAccess(rootExpression, path) {
    return path.reduce((expression, segment) => `${expression}[${JSON.stringify(segment)}]`, rootExpression);
}

function renderHostImportExpression(path) {
    const globalRoot = `(typeof window !== 'undefined' ? window : (typeof self !== 'undefined' ? self : global))`;
    return path.map((segment, index) => index === 0
        ? `${globalRoot}[${JSON.stringify(segment)}]`
        : /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(segment)
            ? `.${segment}`
            : `[${JSON.stringify(segment)}]`).join('');
}

function renderImportBinding(group, entry, moduleRef) {
    if (entry.kind === 'inline_js') return entry.ref;
    const hostImportRef = `__hostImports[${JSON.stringify(group.module)}]?.[${JSON.stringify(entry.hostName)}]`;
    const fallbackRef = moduleRef
        ? renderHostImportAccess(moduleRef, entry.hostPath)
        : renderHostImportExpression(group.module === '__utu_profile' ? ['__utu_profile', ...entry.hostPath] : entry.hostPath);
    const resolvedRef = `(${hostImportRef} ?? ${fallbackRef})`;
    if (entry.kind === 'value') {
        const valueRef = moduleRef ? resolvedRef : hostImportRef;
        return `(() => { const __value = ${valueRef}; if (__value === undefined) throw new Error(${JSON.stringify(`Missing host import "${group.module}.${entry.hostName}"`)}); return __value; })()`;
    }
    const caughtFallback = renderCaughtFallback(entry.returnType);
    return caughtFallback === null
        ? resolvedRef
        : `(...__args) => { try { return ${resolvedRef}(...__args); } catch { return ${caughtFallback}; } }`;
}

function parseReturnTypeNode(node) {
    if (!node) return null;
    if (childOfType(node, 'void_type')) return null;
    const components = [];
    for (let index = 0; index < node.children.length; index += 1) {
        const child = node.children[index];
        if (!child.isNamed || child.type === 'void_type') continue;
        const hash = node.children[index + 1]?.type === '#';
        const err = hash && node.children[index + 2]?.isNamed ? node.children[index + 2] : null;
        components.push(hash && err ? { kind: 'exclusive' } : { kind: child.type === 'nullable_type' ? 'nullable' : 'plain' });
        if (hash) index += err ? 2 : 1;
    }
    return components;
}

function renderCaughtFallback(returnType) {
    if (!returnType?.length) return null;
    if (returnType.length === 1) {
        return returnType[0].kind === 'nullable'
            ? 'null'
            : returnType[0].kind === 'exclusive'
                ? '[null, null]'
                : null;
    }
    return `[${returnType.map(component => component.kind === 'exclusive' ? 'null, null' : 'null').join(', ')}]`;
}
