import { rootNode, childOfType, hasAnon, walk, stringLiteralValue } from './tree.js';

export function jsgen(treeOrNode, binary) {
    const { strings, importFns, importVals, exportNames } = analyze(rootNode(treeOrNode));
    const b64 = toBase64(binary);
    const needsImports = importFns.length > 0 || importVals.length > 0;
    const lines = [
        '// Generated by utu compiler — do not edit',
        '',
        `const __b64 = "${b64}";`,
        '',
        'function __decodeBase64(s) {',
        '  const bin = atob(s);',
        '  const out = new Uint8Array(bin.length);',
        '  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);',
        '  return out;',
        '}',
        '',
    ];

    if (strings.length > 0) {
        lines.push('const __strings = [');
        for (const value of strings) lines.push(`  ${JSON.stringify(value)},`);
        lines.push('];', '');
    }

    if (needsImports) {
        const fields = [
            ...importFns.map(({ name, params }) => `${name}: (${params.map((_, i) => `a${i}`).join(', ')}) => any`),
            ...importVals.map(({ name }) => `${name}: any`),
        ].join(', ');
        lines.push(`/** @param {{ ${fields} }} imports */`);
    }

    lines.push(`export async function instantiate(${needsImports ? 'imports = {}' : ''}) {`);
    lines.push('  const bytes = __decodeBase64(__b64);', '');
    lines.push('  // JS String Builtins: engine resolves "wasm:js-string" imports automatically');
    lines.push('  const module = await WebAssembly.compile(bytes, { builtins: ["js-string"] });', '');
    lines.push('  const importObject = {');

    if (strings.length > 0) {
        lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [String(i), s])),');
    }

    if (needsImports) {
        lines.push('    "es": {');
        for (const { name } of importFns) lines.push(`      ${JSON.stringify(name)}: imports.${name},`);
        for (const { name } of importVals) lines.push(`      ${JSON.stringify(name)}: imports.${name},`);
        lines.push('    },');
    }

    lines.push('  };', '');
    lines.push('  const instance = await WebAssembly.instantiate(module, importObject);');
    lines.push('  return instance.exports;');
    lines.push('}');

    if (exportNames.length > 0) {
        lines.push('', '// Re-export individual functions after instantiation');
        lines.push('// Usage: const { main } = await instantiate(imports);');
        lines.push(`// Exported functions: ${exportNames.join(', ')}`);
    }

    return lines.join('\n');
}

function analyze(root) {
    const strings = new Map();
    const importFns = [];
    const importVals = [];
    const exportNames = [];
    const addString = (value) => {
        if (!strings.has(value)) strings.set(value, strings.size);
    };
    const scanStrings = (node) => walk(node, child => {
        const value = stringLiteralValue(child);
        if (value !== null) addString(value);
    });

    for (const item of root.namedChildren) {
        switch (item.type) {
            case 'fn_decl':
                scanStrings(childOfType(item, 'block'));
                break;
            case 'export_decl': {
                const fn = childOfType(item, 'fn_decl');
                exportNames.push(childOfType(fn, 'identifier').text);
                scanStrings(childOfType(fn, 'block'));
                break;
            }
            case 'global_decl':
                scanStrings(item.namedChildren.at(-1));
                break;
            case 'import_decl':
                if (item.namedChildren[0].text.slice(1, -1) !== 'es') break;
                if (hasAnon(item, '(')) {
                    importFns.push({
                        name: item.namedChildren[1].text,
                        params: childOfType(item, 'import_param_list')?.namedChildren ?? [],
                    });
                } else {
                    importVals.push({ name: item.namedChildren[1].text });
                }
                break;
        }
    }

    return { strings: [...strings.keys()], importFns, importVals, exportNames };
}
function toBase64(bytes) {
    if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('base64');
    let bin = '';
    for (const byte of bytes) bin += String.fromCharCode(byte);
    return btoa(bin);
}
