// compiler/jsgen.js
//
// JS shim generator — produces an ESM module that wraps the compiled Wasm binary.
//
// The generated module:
//   - Embeds the Wasm binary as base64
//   - Provides string literal globals for the "__strings" import namespace
//   - Accepts user-supplied "es" imports matching declared `import extern "es" ...` items
//   - Compiles with JS String Builtins enabled (builtins: ['js-string'])
//   - Returns { exports } from the instantiated module

/**
 * @param {object}     ast    - AST from parse.js ({ kind: 'program', items: [...] })
 * @param {Uint8Array} binary - compiled Wasm binary from opt.js
 * @returns {string}          - ESM JS module string
 */
export function jsgen(ast, binary) {
    const strings    = collectStrings(ast);
    const importFns  = collectImportFns(ast);
    const importVals = collectImportVals(ast);
    const exportNames = collectExports(ast);

    const b64 = toBase64(binary);
    const lines = [];

    lines.push('// Generated by utu compiler — do not edit');
    lines.push('');

    // Embedded binary
    lines.push(`const __b64 = "${b64}";`);
    lines.push('');
    lines.push('function __decodeBase64(s) {');
    lines.push('  const bin = atob(s);');
    lines.push('  const out = new Uint8Array(bin.length);');
    lines.push('  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);');
    lines.push('  return out;');
    lines.push('}');
    lines.push('');

    // String literal table
    if (strings.length > 0) {
        lines.push('const __strings = [');
        for (const s of strings) lines.push(`  ${JSON.stringify(s)},`);
        lines.push('];');
        lines.push('');
    }

    // JSDoc for the imports parameter
    const needsImports = importFns.length > 0 || importVals.length > 0;
    if (needsImports) {
        const fields = [
            ...importFns.map(f => {
                const params = f.params.map((_, i) => `a${i}`).join(', ');
                return `${f.name}: (${params}) => any`;
            }),
            ...importVals.map(v => `${v.name}: any`),
        ].join(', ');
        lines.push(`/** @param {{ ${fields} }} imports */`);
    }

    const paramList = needsImports ? 'imports = {}' : '';
    lines.push(`export async function instantiate(${paramList}) {`);
    lines.push('  const bytes = __decodeBase64(__b64);');
    lines.push('');
    lines.push('  // JS String Builtins: engine resolves "wasm:js-string" imports automatically');
    lines.push('  const module = await WebAssembly.compile(bytes, { builtins: ["js-string"] });');
    lines.push('');

    // Build import object
    lines.push('  const importObject = {');

    if (strings.length > 0) {
        lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [String(i), s])),');
    }

    if (needsImports) {
        lines.push('    "es": {');
        for (const f of importFns)  lines.push(`      ${JSON.stringify(f.name)}: imports.${f.name},`);
        for (const v of importVals) lines.push(`      ${JSON.stringify(v.name)}: imports.${v.name},`);
        lines.push('    },');
    }

    lines.push('  };');
    lines.push('');
    lines.push('  const instance = await WebAssembly.instantiate(module, importObject);');
    lines.push('  return instance.exports;');
    lines.push('}');

    // Named re-exports as a convenience (tree-shakeable)
    if (exportNames.length > 0) {
        lines.push('');
        lines.push('// Re-export individual functions after instantiation');
        lines.push('// Usage: const { main } = await instantiate(imports);');
        lines.push(`// Exported functions: ${exportNames.join(', ')}`);
    }

    return lines.join('\n');
}

// ==================== AST walkers ====================

function collectStrings(ast) {
    const seen = new Map(); // value -> index
    const list = [];
    const visitExpr = (e) => {
        if (!e) return;
        if (e.kind === 'string') {
            if (!seen.has(e.value)) { seen.set(e.value, list.length); list.push(e.value); }
            return;
        }
        for (const v of Object.values(e)) {
            if (Array.isArray(v)) v.forEach(c => c && typeof c === 'object' && c.kind && visitExpr(c));
            else if (v && typeof v === 'object' && v.kind) visitExpr(v);
        }
    };
    const visitBlock = (b) => b.stmts.forEach(visitExpr);
    for (const item of ast.items) {
        if (item.kind === 'fn_decl' || (item.kind === 'export_decl' && item.fn)) {
            visitBlock(item.kind === 'fn_decl' ? item.body : item.fn.body);
        }
        if (item.kind === 'global_decl') visitExpr(item.value);
    }
    return list;
}

function collectImportFns(ast) {
    return ast.items
        .filter(it => it.kind === 'import_fn' && it.module === 'es')
        .map(it => ({ name: it.name, params: it.params }));
}

function collectImportVals(ast) {
    return ast.items
        .filter(it => it.kind === 'import_val' && it.module === 'es')
        .map(it => ({ name: it.name }));
}

function collectExports(ast) {
    return ast.items
        .filter(it => it.kind === 'export_decl')
        .map(it => it.fn.name);
}

// ==================== Base64 ====================

function toBase64(bytes) {
    // Works in both browser and Node/Bun
    if (typeof Buffer !== 'undefined') {
        return Buffer.from(bytes).toString('base64');
    }
    let bin = '';
    for (const b of bytes) bin += String.fromCharCode(b);
    return btoa(bin);
}
