import { rootNode, childOfType, hasAnon, walk, stringLiteralValue } from './tree.js';

export function jsgen(treeOrNode, binary) {
    const { strings, importFns, importVals, exportNames } = analyze(rootNode(treeOrNode));
    const needsImports = importFns.length || importVals.length;
    const lines = [
        '// Generated by utu compiler — do not edit',
        '',
        `const __b64 = "${toBase64(binary)}";`,
        '',
        'const __decodeBase64 = s => {',
        '  const bin = atob(s), out = new Uint8Array(bin.length);',
        '  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);',
        '  return out;',
        '};',
    ];

    if (strings.length) lines.push('', `const __strings = [${strings.map(value => JSON.stringify(value)).join(', ')}];`);

    if (needsImports) {
        const fields = [
            ...importFns.map(({ name, params }) => `${name}: (${params.map((_, i) => `a${i}`).join(', ')}) => any`),
            ...importVals.map(({ name }) => `${name}: any`),
        ].join(', ');
        lines.push('', `/** @param {{ ${fields} }} imports */`);
    }

    lines.push('', `export async function instantiate(${needsImports ? 'imports = {}' : ''}) {`);
    lines.push('  const module = await WebAssembly.compile(__decodeBase64(__b64), { builtins: ["js-string"] });');
    lines.push('  const instance = await WebAssembly.instantiate(module, {');
    if (strings.length) lines.push('    "__strings": Object.fromEntries(__strings.map((s, i) => [String(i), s])),');
    if (needsImports) {
        lines.push('    "es": {');
        for (const { name } of [...importFns, ...importVals]) lines.push(`      ${JSON.stringify(name)}: imports.${name},`);
        lines.push('    },');
    }
    lines.push('  });', '  return instance.exports;', '}');
    if (exportNames.length) lines.push('', `// Exported functions: ${exportNames.join(', ')}`);

    return lines.join('\n');
}

function analyze(root) {
    const strings = new Map(), importFns = [], importVals = [], exportNames = [];
    const scanStrings = (node) => walk(node, child => {
        const value = stringLiteralValue(child);
        if (value !== null && !strings.has(value)) strings.set(value, strings.size);
    });

    for (const item of root.namedChildren) {
        switch (item.type) {
            case 'fn_decl': scanStrings(childOfType(item, 'block')); break;
            case 'export_decl': {
                const fn = childOfType(item, 'fn_decl');
                exportNames.push(childOfType(fn, 'identifier').text);
                scanStrings(childOfType(fn, 'block'));
                break;
            }
            case 'global_decl': scanStrings(item.namedChildren.at(-1)); break;
            case 'import_decl': {
                if (item.namedChildren[0].text.slice(1, -1) !== 'es') break;
                const fn = hasAnon(item, '(');
                (fn ? importFns : importVals).push(fn
                    ? { name: item.namedChildren[1].text, params: childOfType(item, 'import_param_list')?.namedChildren ?? [] }
                    : { name: item.namedChildren[1].text });
                break;
            }
        }
    }

    return { strings: [...strings.keys()], importFns, importVals, exportNames };
}

function toBase64(bytes) {
    if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('base64');
    let bin = '';
    for (const byte of bytes) bin += String.fromCharCode(byte);
    return btoa(bin);
}
